// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code
		int count = Integer.parseInt(args[0]);

		int above = 0;
		int below = 0;
		for (int i = 0; i < count; i++)
		{
			double random =Math.random();
			if (random > 0.5)
			{
				above++;
			}
			else
			{
				below++;
			}
		}
		System.out.println("> 0.5: " + above);
		System.out.println("<= 0.5: " + below);
		if (below == 0)
		{
		    System.out.println("Ratio: Infinity");
		}
		 else 
		{
			double ratio = (double) above / (double) below;
			if( ratio > 1.0 )
			{
				ratio = 1.0 / ratio;
			}
			System.out.println("Ratio:" + ratio);
		}
	}
}
